[package]
name = "Trait"
version = "0.1.0"
authors = ["v_yekgong <Gygy199806>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
